version: '3.0'  # 使用 Docker Compose 的版本 3.0，適合大部分部署場景

services:
  api:  # 定義一個服務，名稱為 api
    image: wade52/tibame_api:${DOCKER_IMAGE_VERSION}  # 使用的映像檔名稱與標籤（版本）
    hostname: "api.{{.Task.Slot}}"  # 設定 hostname = api
    command: pipenv run uvicorn src.api.main:app --reload --host 0.0.0.0 --port 8888
    ports: 
      - 8888:8888
    deploy:
      mode: replicated
      replicas: 1
      placement:
        # 設定在
        # node label api = true 的機器上執行
        constraints: [node.labels.api == true]

    restart: always  # 若容器停止或崩潰，自動重新啟動
    environment:
      - TZ=Asia/Taipei  # 設定時區為台北（UTC+8）
    networks:
      - my_swarm_network  # 將此服務連接到 my_swarm_network 網路

networks:
  my_swarm_network:
    # 加入已經存在的網路
    external: true
